name: Проверка схем (PR)

on:
  pull_request:
    branches:
      - main # Или ваша основная ветка

jobs:
  call_schema_check:
    name: Проверить изменения схемы
    # ❗️ КЛЮЧЕВОЕ ИЗМЕНЕНИЕ: Ссылка на центральный репозиторий 'c'
    uses: khandramai/c/.github/workflows/reusable_schema_check.yml@main
    with:
      pull_request_number: ${{ github.event.pull_request.number }}
      head_sha: ${{ github.event.pull_request.head.sha }}
      base_sha: ${{ github.event.pull_request.base.sha }}
      schema_path: 'ramls' # <-- Убедитесь, что этот путь актуален для репозитория A/B
    secrets: inherit # Передаем все доступные секреты